"""Methodology content for Disease Exposure — RMT concept + data-source options."""

from __future__ import annotations

from htmltools import HTML, TagList, tags

from src.ui.methodology_common import model_questions_block, source_card


def disease_methodology_section() -> TagList:
    """Colleague RMT-based concept note + candidate data sources for team decision."""
    return TagList(
        tags.h3("Disease Exposure — methodology concept"),
        tags.p(
            "The disease exposure dimension assesses the likelihood that a country will be "
            "exposed to an animal-health shock through the introduction or spread of a specific "
            "transboundary animal disease. For the prototype, this dimension will be based on an "
            "adaptation of the Risk Monitoring Tool (RMT), developed by the European Commission "
            "for the Control of Foot-and-Mouth Disease (EuFMD) in collaboration with FAO. The RMT "
            "is a semi-quantitative risk assessment framework designed to support countries in "
            "identifying and ranking the most relevant sources and pathways for disease "
            "introduction. It combines epidemiological information, pathway characteristics and "
            "country-to-country connections to produce a comparative estimate of entry risk."
        ),
        tags.p(
            "Within the RMT framework, the country being assessed is defined as the "
            "target country, while all other countries that may act as potential sources of "
            "infection are defined as source countries. The methodology ranks the relative "
            "probability of disease introduction from each source country to the target country "
            "by evaluating four main components:"
        ),
        tags.ul(
            tags.li(
                TagList(
                    tags.strong("Disease status and circulation in source countries: "),
                    "the extent and intensity of pathogen circulation, based on the most recent "
                    "available epidemiological information, including disease occurrence, "
                    "geographical distribution and frequency of outbreaks.",
                )
            ),
            tags.li(
                TagList(
                    tags.strong("Mitigation measures in source countries: "),
                    "the presence and effectiveness of measures implemented to prevent, control "
                    "or limit disease circulation, thereby reducing the likelihood of "
                    "international spread.",
                )
            ),
            tags.li(
                TagList(
                    tags.strong("Pathway suitability: "),
                    "the ability of the pathogen to spread through different transmission "
                    "pathways. Pathways considered include airborne transmission, vectors, "
                    "wildlife, animal products, movements of live animals and fomites. The "
                    "relative importance of each pathway depends on the epidemiological "
                    "characteristics of the disease under consideration.",
                )
            ),
            tags.li(
                TagList(
                    tags.strong("Country-to-country connections: "),
                    "the strength of the connections linking source and target countries. These "
                    "may include trade flows, geographical proximity, transportation routes and "
                    "other forms of interaction that can facilitate disease spread through one "
                    "or more pathways.",
                )
            ),
        ),
        tags.p(
            "For each component, predefined criteria are used to assign standardised scores. In "
            "the original RMT, these scores are generated by national experts using locally "
            "available information. For the purposes of the Trade Vulnerability Index, the "
            "approach will be adapted to a global scale by deriving the required scores from "
            "international datasets and harmonised assumptions, thereby ensuring comparability "
            "across countries."
        ),
        tags.p(
            "The primary epidemiological source will be the WOAH World Animal Health Information "
            "System (WAHIS), which will be used to identify the countries included in the "
            "assessment and to estimate current disease circulation levels. These data will "
            "provide the basis for the disease status scores assigned to each source country. "
            "Additional scores will be generated for mitigation measures, pathway relevance and "
            "country-to-country connections using internationally available databases and proxy "
            "indicators where direct measurements are unavailable. For example, transportation "
            "connectivity, travel volumes and trade statistics may be used as proxies for the "
            "intensity of interactions between countries."
        ),
        tags.p(
            "The resulting risk score represents a relative measure of disease-entry risk "
            "associated with each source-target country pair and pathway combination. A higher "
            "score indicates a greater likelihood that a disease could enter the target country "
            "from a specific source country through a particular transmission pathway. The "
            "analysis can then be repeated iteratively, rotating each country in turn as the "
            "target country, thereby producing a global matrix of relative disease exposure."
        ),
        tags.p(
            "The final output will identify the international connections, trade relationships "
            "and movement networks that contribute most strongly to a country’s exposure under "
            "current epidemiological conditions. Beyond its application within the Trade "
            "Vulnerability Index, the framework could also serve as a dynamic monitoring tool, "
            "allowing exposure patterns to be periodically reassessed as disease situations "
            "evolve, new outbreaks occur, mitigation measures change or alternative scenarios "
            "are simulated."
        ),
        tags.div(
            {"class": "tvi-callout"},
            HTML(
                "<strong>Current prototype status:</strong> Disease Exposure uses "
                "<strong>EuFMD RMT curated disease-status and mitigation</strong> for the "
                "neighbourhood country set extracted from "
                "<code>RMT_FAST_EuFmd_Clean_rv20231017.xlsx</code>, with Nexus pathway "
                "effectiveness and <strong>provisional pathway connections</strong>. "
                "Countries without curated status are <strong>N/A</strong> (never zero). "
                "WAHIS event extracts, WOAH official FMD status lists, and bilateral "
                "Comtrade/proximity connections are the next data layers to expand coverage."
            ),
        ),
        tags.h3("Disease Exposure data sources — options for team decision"),
        tags.p(
            "WAHIS is proposed as the main epidemiological source for disease status/circulation. "
            "Other sources support mitigation, pathway and connectivity components of the "
            "RMT adaptation. Colleagues should decide which enter the scored model versus "
            "remain contextual."
        ),
        tags.div(
            {"class": "tvi-source-grid"},
            source_card(
                "WAHIS (WOAH World Animal Health Information System)",
                "MAIN SOURCE — Disease status & circulation",
                "Near-global Member reporting of Listed (and emerging) diseases since ~2005; "
                "immediate notifications, follow-ups and six-monthly reports. Completeness and "
                "timeliness vary by country and disease; wildlife/non-listed coverage is thinner.",
                "Public interface for consultation/export. Report-list / report-detail query "
                "endpoints can support automated, cached ingest (no live dependency required "
                "for the Shiny app once Parquet/CSV is built).",
                "Primary basis for source-country disease status scores (occurrence, distribution, "
                "outbreak frequency) in the RMT adaptation; defines which countries enter the "
                "global exposure matrix for the selected disease (prototype: FMD).",
                "Implement as the first real Disease Exposure input: build a cached WAHIS extract "
                "for FMD (and later other diseases), map to standardised circulation scores "
                "(e.g. free / sporadic / endemic intensity bands), and feed the source-country "
                "leg of the RMT. Refresh periodically for dynamic monitoring.",
                primary=True,
            ),
            source_card(
                "WOAH Official disease status & self-declarations",
                "MAIN / HIGH-PRIORITY — Disease status (and mitigation context)",
                "Official recognition for selected diseases (including FMD freedom with/without "
                "vaccination and endorsed official control programmes) is public and "
                "trade-critical. Self-declarations apply to other diseases and are not WOAH "
                "endorsement; FMD uses official recognition rather than self-declaration "
                "publication.",
                "Public status lists and dossiers on woah.org. Largely structured download or "
                "manual table extract; cache locally. No single API equivalent to a full PVS "
                "CC matrix.",
                "Anchors disease status of source (and target) countries for FMD: free / free "
                "with vaccination / infected / endorsed programme. Complements WAHIS event data "
                "with formally recognised status. Can also inform mitigation (control programme "
                "endorsement) as a coarse proxy.",
                "Include under Disease Exposure. Use as an ordinal status score in "
                "the RMT disease-status component, and optionally as a map overlay. Keep "
                "distinct from Legal IV-6/IV-7 (capacity to zone/compartmentalise) versus "
                "achieved disease-free recognition.",
                primary=True,
            ),
            source_card(
                "EuFMD / FAO Risk Monitoring Tool (RMT) documentation & national applications",
                "Methodological backbone",
                "Framework and scoring criteria exist for expert-based national RMT use; "
                "global TVI adaptation must replace expert elicitation with international "
                "datasets. Published national RMT exercises are country-specific, not a global panel.",
                "Manual use of EuFMD/FAO guidance and templates; no global scored API.",
                "Defines the four components, pathway list and scoring logic that Disease "
                "Exposure should implement. Does not itself supply worldwide numeric inputs.",
                "Codify RMT criteria in config (pathway weights per disease, score bands) and "
                "document every proxy mapping. Treat national RMT case studies as validation "
                "benchmarks for a few demo countries, not as production inputs.",
            ),
            source_card(
                "UN Comtrade & FAOSTAT (shared caches — see Economic Sensitivity)",
                "Shared input — Country-to-country connections / host context",
                "Trade and livestock production statistics are maintained primarily for Economic "
                "Sensitivity. Coverage and access are described in that section.",
                "Reuse the project’s curated UN Comtrade and FAOSTAT extracts (no second ingest).",
                "Comtrade bilateral intensities proxy live-animal and product pathway connections "
                "in the RMT; FAOSTAT livestock numbers may optionally scale pathway/host relevance.",
                "Do not add a separate Disease Exposure weight for these series in the TVI — "
                "score them under Economic Sensitivity and reuse the matrices here for exposure "
                "pathways only.",
            ),
            source_card(
                "Transport & mobility proxies (air, maritime, road/proximity)",
                "Enhancement — Country-to-country connections",
                "Partial global coverage depending on dataset (e.g. flight connectivity, port "
                "traffic, shared borders). Rarely disease-specific; informal cross-border "
                "movement is poorly observed.",
                "Mix of open datasets and licensed commercial sources; prefer open proxies "
                "first (contiguous borders, distance, public transport statistics). Manual "
                "assembly + cache.",
                "Proxies for fomite / passenger / logistics pathways and for geographical "
                "proximity as a connection strength.",
                "Phase 2 of RMT connections: add a simple proximity + selected transport "
                "connectivity score alongside trade. Avoid over-weighting tourism unless "
                "pathway analysis for FMD supports it.",
            ),
            source_card(
                "PVS disease prevention/control competencies (selected CCs)",
                "Enhancement — Mitigation measures in source countries",
                "Same PVS coverage limits as Legal (not all countries public; different years/"
                "tool editions). CCs on surveillance, emergency response, etc. are capacity "
                "proxies, not measured field effectiveness.",
                "Same as Legal: public PDFs / PVSIS extract / approved CSV; no public bulk CC API.",
                "Proxy for mitigation strength in source countries within the RMT (reducing "
                "likelihood of international spread).",
                "Optional: reuse a small bundle of disease-control CCs as a mitigation score "
                "in Disease Exposure — keep separate from Legal Preparedness (IV-1/IV-4/IV-6/IV-7) "
                "to avoid conceptual overlap. Team to decide weights.",
            ),
            source_card(
                "WOAH Observatory (disease / standard-uptake indicators)",
                "Enhancement / triangulation",
                "Published indicators and dashboards on standard implementation and related "
                "themes; country detail and refresh cycles vary; some inputs overlap WAHIS/PVS/WTO.",
                "Report PDFs, indicator matrix, data catalogue (XLSX); dashboards often "
                "semi-manual extract.",
                "External benchmark for whether exposure patterns align with Observatory "
                "findings; not the core RMT engine.",
                "Use for methodology triangulation and narrative in Country profile; do not "
                "double-count series already taken from WAHIS or PVS.",
            ),
        ),
        model_questions_block(
            "Questions for colleagues — Disease Exposure mathematical model",
            "Please answer these so we can replace the mock module with a coded RMT adaptation "
            "(formulas, weights, missing-data rules). Leave blank where still undecided.",
            [
                "For FMD, which transmission pathways are in scope for v1 (live animals, animal "
                "products, fomites, wildlife, airborne, vectors, other), and what relative weights "
                "should each pathway receive?",
                "How should WAHIS data be turned into a source-country disease-status score "
                "(e.g. free / sporadic / endemic bands)? Which time window (last 12 / 24 / 60 months) "
                "and which metrics (outbreak count, affected admin areas, persistence)?",
                "How should WOAH official FMD status (free / free with vaccination / infected / "
                "endorsed control programme) map to numeric scores, and how does it combine with "
                "WAHIS event data when they disagree?",
                "What is the mathematical form of a source→target pathway risk "
                "(e.g. status × mitigation × pathway suitability × connection)? Additive, "
                "multiplicative, or log-linear? Any caps or floors?",
                "How is mitigation scored for source countries in v1 (official control programme "
                "only; selected PVS CCs; expert constants; omit until later)?",
                "How should UN Comtrade connection strength be measured (export value, quantity, "
                "share of target imports, log-transform) and normalised to the RMT scale?",
                "How do we aggregate the full source×pathway matrix into one country Disease "
                "Exposure Index 0–100 (sum, max, top-k sources, distance-weighted)?",
                "Should a country’s own domestic circulation enter Disease Exposure, or is "
                "domestic status only context while Exposure = entry risk from abroad?",
                "Missing-data rules: if WAHIS or status is missing for a source, drop the link, "
                "impute a default, or mark the target country’s Exposure as partial/N/A?",
                "How often should the exposure matrix be refreshed for “dynamic monitoring”, "
                "and do we version scores by reference date?",
                "Which 3–5 countries should be used to validate the global RMT proxies against "
                "existing national EuFMD/FAO RMT exercises?",
            ],
        ),
        tags.h3("Suggested decision path for Disease Exposure"),
        tags.ol(
            tags.li(
                TagList(
                    tags.strong("Confirm RMT adaptation"),
                    " as the Disease Exposure engine (four components; global proxies instead of "
                    "national expert scoring).",
                )
            ),
            tags.li(
                TagList(
                    tags.strong(
                        "Implement WOAH disease-status inputs first "
                        "(WAHIS event/reporting data + official FMD status)"
                    ),
                    " — WAHIS is WOAH’s animal health information system; official status is "
                    "WOAH’s recognised freedom/control-programme listing. Together they replace "
                    "the mock Disease Exposure module for the disease-status component.",
                )
            ),
            tags.li(
                TagList(
                    "Add ",
                    tags.strong("connection layers"),
                    " by reusing the Economic Sensitivity UN Comtrade cache for trade pathways, "
                    "then proximity/transport.",
                )
            ),
            tags.li(
                "Agree pathway weights for FMD and how mitigation will be proxied "
                "(official control programmes, selected PVS CCs, or both)."
            ),
            tags.li(
                "Produce the source–target exposure matrix, aggregate to a country Disease "
                "Exposure Index (0–100), and expose top contributing links in the Country profile."
            ),
        ),
    )
